import "./globals.css";
import React from "react";
import { Inter } from "next/font/google";
import Providers from "@/utils/provider";
import WebThreeProviders from "@/utils/thirdwebProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WebThreeProviders>
          <Providers>{children}</Providers>
        </WebThreeProviders>
      </body>
    </html>
  );
}
